version: '3'
volumes:
  reports:

services:
  perf-test:
    command: ./run
    volumes:
     - ./reports:/lighthouse/reports
     - ./test/suites:/lighthouse/test/suites
    build: 
      context: ./
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - no_proxy=${NO_PROXY}
    
